### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by jasonqiao** [uMeetMe/uMeetMe#3]
I have made a new logo which should be applied to the main page.

<img width="491" alt="logo" src="https://cloud.githubusercontent.com/assets/13429203/11013202/f010be90-84d0-11e5-827b-7767d072dce2.png">

**Comment by adamnew123456** [comment]
I'm working on simplifying the homepage radically. It should be a lot easier to work with without so many excessive CSS classes and divs.

**Comment by jasonqiao** [comment]
Ok good! Looking forward!

**Comment by adamnew123456** [comment]
I'll push the newest version to Heroku in a sec.

**Comment by jasonqiao** [comment]
can't wait!

**Comment by adamnew123456** [comment]
[Deployed](http://protected-atoll-6958.herokuapp.com/)

**Comment by jasonqiao** [comment]
AWESOME! I love it!
